name: deploy nodesjs app
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    step:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Execute Remote ssh 
        uses: actions/ssh-action@v4
        with:
          host: $${{ secrets.project1 }}
          username: ${{ secret.ec2_username }}
          key: $ {{ secrets.ec2_ssh_key }}
          script: |
              cd ~/project1
              git pull origin main
              npm install --production 
              pm2 restart node-app || pm2 start server.js --name "node-app" 
          
        
